### ISSUE TITLE
Can not install through "helm plugin"

### ISSUE THREAD

**Issue by drzero42** [ContainerSolutions/helm-convert#20]
When installing I get this error:

```
abo@bofh42:~$ helm plugin install https://github.com/ContainerSolutions/helm-convert
sh: 1: /home/abo/.helm/plugins/helm-convert/install.sh: not found
Error: plugin install hook for "convert" exited with error
```

I'm on Helm 2.12.3 on an Ubuntu 18.04 AMD64 system with golang 1.10 installed.

**Comment by etiennetremel** [comment]
Oops, my bad @drzero42, the file was in fact missing. I just added it, could you try again?

**Comment by drzero42** [comment]
That made it work! :)
Now I am facing another problem though. The example from the documentation works fine:
```
abo@ernest:~/tmp$ helm convert --destination mongodb --name mongodb stable/mongodb
```
But when I try it with `stable/ark` (one of the helm charts I want to use with Kustomize), it errors out like this:
```
abo@ernest:~/tmp$ helm convert --destination ark --name ark stable/ark
panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 1 [running]:
github.com/ContainerSolutions/helm-convert/pkg/transformers.(*secretTransformer).Transform(0x1426970, 0xc001a76dc0, 0xc003627a20, 0x0, 0x0)
	/home/travis/gopath/src/github.com/ContainerSolutions/helm-convert/pkg/transformers/secret.go:50 +0x924
github.com/ContainerSolutions/helm-convert/pkg/transformers.(*multiTransformer).Transform(0xc00348ffc0, 0xc001a76dc0, 0xc003627a20, 0x8, 0xc000121b28)
	/home/travis/gopath/src/github.com/ContainerSolutions/helm-convert/pkg/transformers/multitransformer.go:27 +0x79
github.com/ContainerSolutions/helm-convert/cmd.(*convertCmd).run(0xc00008ef00, 0xc000121d88, 0xc000121d58)
	/home/travis/gopath/src/github.com/ContainerSolutions/helm-convert/cmd/convert.go:255 +0xc3b
github.com/ContainerSolutions/helm-convert/cmd.NewConvertCommand.func2(0xc000182280, 0xc0000c0be0, 0x1, 0x5, 0x0, 0x0)
	/home/travis/gopath/src/github.com/ContainerSolutions/helm-convert/cmd/convert.go:106 +0x99
github.com/spf13/cobra.(*Command).execute(0xc000182280, 0xc0000b4130, 0x5, 0x5, 0xc000182280, 0xc0000b4130)
	/home/travis/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:762 +0x465
github.com/spf13/cobra.(*Command).ExecuteC(0xc000182280, 0xd584e0, 0xc000121f88, 0xc00009a058)
	/home/travis/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2c0
github.com/spf13/cobra.(*Command).Execute(...)
	/home/travis/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
main.main()
	/home/travis/gopath/src/github.com/ContainerSolutions/helm-convert/main.go:13 +0x44
Error: plugin "convert" exited with error
```

**Comment by etiennetremel** [comment]
Good catch, there was a bug which prevented the transformation of files when the data field of secret resources is empty. Release https://github.com/ContainerSolutions/helm-convert/releases/tag/v0.4.5 has a fix for it. Thanks!
